### ISSUE TITLE
Let's redirect the user to login page after clicking on Activation Link 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/tc-auth-lib#136]
The current behavior is that when the user clicks on the activation button on the activation email, the user is directed to a "start your journey" page where they select Gig Work Vs Practice. The expected behavior is they should FIRST be routed to the Login page THEN taken to the 'start your journey page

**Reference**
https://drive.google.com/drive/folders/16lEJdRuXpsQ5FAJ2ThPrrlAOs5E-096Q?usp=sharing 

Note : Please update the flow for Customer and Member Role.

**Comment by jmgasper** [comment]
@sachin-maheshwari - Should I work on this one?  I thought we weren't going to do this?

**Comment by lakshmiathreya** [comment]
Agree with @drasticdpk - Login should be more prominent right after clicking Activation Link.

**Comment by sachin-maheshwari** [comment]
@jmgasper I already deployed the changes (changes in sendgrid email template only) on DEV for QA. I think QA is verifying the changes.

**Comment by coderhacker** [comment]
@sachin-maheshwari , This is not fixed on dev as per the above scenario. 

https://user-images.githubusercontent.com/62358241/122348584-efb38480-cf68-11eb-95cb-150e1a0a88ca.mp4

**Comment by coderhacker** [comment]
Prod verification: 

https://user-images.githubusercontent.com/62358241/122396092-48991200-cf95-11eb-9d1c-bc1d657b3829.mp4

**Comment by Oanh-and-only-Oanh** [comment]
The expected behavior is they should FIRST be routed to the Login page THEN taken to the page they clicked “sign up”

**Comment by sachin-maheshwari** [comment]
@coderhacker just FYI, its not deployed on Prod yet.

**Comment by drasticdpk** [comment]
@sachin-maheshwari , 
Here is my observation 
1. User selection window is always pointing to prod env, so unable to test from here. 
![image](https://user-images.githubusercontent.com/25297859/122528829-79805200-d03c-11eb-8d0d-c3e3a2ba77cf.png)

2. Sign up for Challenge Listing  and Connect app dev  env is working as expected

https://user-images.githubusercontent.com/25297859/122528010-99634600-d03b-11eb-820c-626042fee582.mp4


3.

**Comment by sachin-maheshwari** [comment]
@drasticdpk I didn't get what you want say here. From DEV, you reached to Prod.

**Comment by drasticdpk** [comment]
Hi @sachin-maheshwari  and Team, 
issue has been fix on  prod env and it is verified.
